### PR TITLE
Added SUT/ Error Handling/ Fixed Bugs

### LINKED ISSUE #48: Handle and test for errors in modView
Test for an empty table, invalid week numbers, no inputs, and auto-resizing of the module code column.

### PR DESCRIPTION
**Pull request by limgl1998**
Fixes #48

### CODE REVIEW

File: src/main/java/seedu/modtracker/Module.java [hunk 1]
```diff
@@ -8,24 +8,26 @@
  */
 public class Module {
 
-    private String moduleCode;
-    private int expected = -1;
-    private double[] actualTime = new double[13];
+    public static final int NO_INPUT = -1;
+    public static final int INDEX_OFFSET = 1;
+    private final String moduleCode;
```
Comment (KennethEer) [inline src/main/java/seedu/modtracker/Module.java]: I think the moduleCode should not be set as final for future extendibility, so in case if the user has already typed in the expected and actual time for a module, and after that the user realises the module code is wrong, the user can edit the module code if the module code is not final, but still retain the expected and actual time.

File: src/main/java/seedu/modtracker/Module.java [hunk 2]
```diff
@@ -8,24 +8,26 @@
...
+    private int expected = NO_INPUT;
+    private final double[] actualTime = new double[13];
```
Comment (KennethEer) [inline src/main/java/seedu/modtracker/Module.java:15]: The actual time should not be set as final, so it can be changed later on

**Review by KennethEer — COMMENTED** [review]
Looks good, some comments on the type of variable

File: src/main/java/seedu/modtracker/Module.java (hunk 1 above)
Comment (limgl1998) [reply src/main/java/seedu/modtracker/Module.java]: Okay sure will change it back
